Dev/front end
EugeneBatenko/carpatian-knights pull request #1
Opened 2019-10-29 11:51 UTC by EugeneBatenko

2019-10-29 20:21 UTC, an-drian requested changes
Переглянь пліз всі коменти і пройдись по файлах. Я в багатьох місцях не відмічав, бо коменти б дублювались. Особливо зверни увагу на написання реакт комнонентів.

Помітив що підключена бібліотека react-redux, але немає самого redux. Певно ті ліба надлишкова. Є ще думка стосовно axios. Вона підключена і використовужтсья тільки один раз. Нема доцільності тянути цілу лібу, щоб один запит зробити. Тут треба прийняти рішення, використовувати axios чи fetch. Якшо fetch - тоді axios видалити і ту функцію переписати.
Вроді всьо. Успіху з проектом  :)

2019-10-29 20:21 UTC, an-drian commented on LICENSE
> +                   GNU LESSER GENERAL PUBLIC LICENSE
Не певен, шо той файл потрібен, хіба то у вас open source

2019-10-29 20:21 UTC, an-drian commented on package.json
> +{
Отут напишу. А eslint викортистовуєш? Просто бачу, шо вроді не встановлений в `devDependencies`. Якшо ні, то використовуй :)

2019-10-29 20:21 UTC, an-drian commented on src/App.js
> +    constructor(props) {
Не певен, шо тут в тебе є якісь props, так само, як і в `super()`. Ці змінні не використовується і є лишніми тут

2019-10-29 20:21 UTC, an-drian commented on src/App.js
> +        super.state = {showMenu: true};
Ніколи такого не зустрічав як `super.state`. Вроді має бути `this.state`. але загалом краще уже використовувати functional components + react hooks. 
Якшо таки використовувати class-like components, то можна не писати constructor для кожного компоненту, де буде стейт, а оголошувати його якось так:
```
class BlaBla extends Component {
  state = {
    test: 'Test'
  }
}
```

2019-10-29 20:21 UTC, an-drian commented on src/App.js
> +    }
Краще переписати цю функцію на шось таке:
```
handleClick = () => {
  this.setState(state => ({ showMenu: !state.showMenu }))
}
```

Напиши будь ласка, чому тут `super`? Я просто ніколи такого не бачив і в документації теж. На скільки я розумію, `super.method` є сенс використовувати, якшо ти хочеш викликати з батьківського класу якись метод, так як він його в батьківському не знаходить то викликає з поточного) Тому, думаю, краще юзати `this`. А ще, використовуєчи такий запис не потрібно банйдити this для кожної функції в конструкторі)

2019-10-29 20:21 UTC, an-drian commented on src/App.js
> +                <Router>
Якшо робити такий глобальний роутер, бо є варіант його винести в якись окремий файлик

2019-10-29 20:21 UTC, an-drian commented on src/components/AboutUs.js
> +export default AboutUs;
Додай пропуст в кінці файлу :)

2019-10-29 20:21 UTC, an-drian commented on src/components/ActiveTours.js
> +        fetch(`${API_URL}/activeroutes/`)
Краще запити винести в якусь окрему папку, наприклад api, а там їх уже групувати і тд.

2019-10-29 20:21 UTC, an-drian commented on src/components/ActiveTours.js
> +        super.state = {expand: true};
тут теж не дуже зрозумів логіку використання super. В результі хіба `
this.state = {
            isLoading: true,
            table: [{}],
            error: null,
        };
` не перезапише цей стейт?

2019-10-29 20:21 UTC, an-drian commented on src/components/ActiveTours.js
> +        this.handleClick = this.handleClick.bind(this);
Писав вище. Можна обійтись без цього, якшо питсати оголошення обробника отак
`handleClick = () => { // bla-bla }`

2019-10-29 20:21 UTC, an-drian commented on src/components/ActiveTours.js
> +export default ActiveTours;
Додай пусту строчку :)

2019-10-29 20:21 UTC, an-drian commented on src/components/NewsBlock.js
> +const API_URL = "https://carpatianapi.herokuapp.com";
Це можна винести в ту саму папочку /api і десь потім звідти експортувати. Дуплюється оголошення

2019-10-29 20:21 UTC, an-drian commented on src/components/NewsBlock.js
> +
Надлишкова порошня строчка)

2019-10-29 20:21 UTC, an-drian commented on src/components/NewsBlock.js
> +export default NewsBlock;
пуста строчка в кінці :)

2019-10-29 20:21 UTC, an-drian commented on src/components/PageHeaders.js
> +export default PageHeaders;
Тут теж) Короч, то всіх файлів стосується

2019-10-29 20:21 UTC, an-drian commented on src/components/RulesList.js
> +    state = {
О, а тут стейт оголошений добре

2019-10-29 20:21 UTC, an-drian commented on src/components/SliderGallery.js
> +                    {/*<img src={slide1} alt="1"/>*/}
Можна відмалювати через `map`

2019-10-29 20:21 UTC, an-drian commented on src/pages/News.js
> +
Надлишковий пропуск

2019-10-29 20:21 UTC, an-drian commented on src/scss/layouts/_l-header.scss
> +
Хммм, дивний файлик. Пробіли))

2019-10-29 20:21 UTC, an-drian commented on src/scss/layouts/_l-news-block.scss
> +
Надлишковий пробіл

2019-10-29 20:21 UTC, an-drian commented on src/scss/layouts/_l-person-block.scss
> +
Надлишковий пробіл

2019-10-29 20:21 UTC, an-drian commented on src/scss/layouts/_l-rules-list.scss
> +
І тут

2019-11-03 14:17 UTC, EugeneBatenko commented on package.json
> +{
В мене у WebStrom є ESlint. Але не впевнений в цьому до кінця)

2019-11-03 14:20 UTC, EugeneBatenko commented on src/App.js
> +        super.state = {showMenu: true};
Я прибрав конструктор, не знав, що можна без нього. Спробував з хуками, але не все працювало. Можеш пояснити або кинути статтю якусь за хуки як вони між компонентами працюють, всередині одного я вже розібрався, а як взаємодіяти з іншиними не розібрався)

2019-11-03 14:28 UTC, EugeneBatenko commented on src/components/AboutUs.js
> +export default AboutUs;
Це потрібно для індексації?

2019-11-03 14:45 UTC, EugeneBatenko commented on src/components/ActiveTours.js
> +        fetch(`${API_URL}/activeroutes/`)
Можеш показати приклад як це грамотно зробити?

2019-11-03 15:51 UTC, EugeneBatenko reviewed
Я там в основному повиправляв дрібні помилки. Пробував меню під хуки переробити, але заплутався як взаємодію між компоненатанми робити. Бібліотеку redux підключив бо планував проект на нього перевести і шось все руки не дойдуть)

2019-11-22 20:14 UTC, merged